### ISSUE TITLE
ability to write to postgres db?

### ISSUE THREAD

**Issue by mattrichard-datascience** [rstudio/shinylive#22]
It seems like we can only get data from api's,  is this true? or will shinylive only ever fetch and render?

Would it be possible to send data? ex -  a s3 bucket or a hosted postgres db? 

It seems like having the ability to send data would make this an amazing and simple webapp framework.

thoughts?

**Comment by wch** [comment]
The limitations on Shinylive come from the web browser's security sandbox, so it will be able to do the same things as any other web application that runs in the browser. In addition to being able to talk to web APIs, it can use websockets, for example, but you'll need something running on the backend to receive messages from the browser.
